apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: scc-app-svc
spec:
  selector:
    app: scc-app
  ports:
    - protocol: TCP
      port: 8081 # The port that the service is running on in the cluster
      nodePort: 30097
      targetPort: 8081
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: scc-app
spec:
  selector:
    matchLabels:
      app: scc-app
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: scc-app
    spec:
      containers:
        - name: scc-app
          image: pdimas12/scc-app:prd20 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081 # The port that the container is running on in the cluster
          volumeMounts:
            - name: images
              mountPath: /images
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: pv1-claim