apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  hostPath:
    path: "/mnt/images"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv1-claim
spec:
  volumeName: pv1
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 2Gi